#!/usr/bin/expect -f
spawn python ./awslogs-agent-setup.py --region us-west-2
expect "AWS Access Key ID:"
send "\n"
expect "AWS Secret Access Key:"
send "\n"
expect "Default region name:"
send "\n"
expect "Default output format:"
send "\n"
expect "Path of log file to upload:"
send "\n"
expect "Destination Log Group name:"
send "\n"
expect "Enter choice:"
send "\n"
expect "Enter choice:\r"
send "\n"
expect "Enter choice:\r"
send "\n"
expect "More log files to configure?:"
send "N\n"
expect "$ "